### ISSUE TITLE
Install cant run on PHP 7.0

### ISSUE THREAD

**Issue by alar77** [boonex/dolphin.pro#636]
/install/index.php  line 56
`set_magic_quotes_runtime(0);`
which has been removed in php 7.x,x
Change to
`if (version_compare(phpversion(),"7.0.0","<")) {`
`    set_magic_quotes_runtime(0);`
`}`
to fix it

**Comment by begrafx** [comment]
Would this cause MAMP to give a 500 error, and show "client denied by server configuration" when I attempt to run the install.php file?

**Comment by begrafx** [comment]
OK, I made the change given above, and was able to get the install to START, however part way through, I get the 500 error AGAIN, this time with this in the log:

[24-Aug-2018 14:56:45 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /Applications/MAMP/htdocs/dolphin/install/index.php:1350
Stack trace:
#0 /Applications/MAMP/htdocs/dolphin/install/index.php(449): CheckSQLParams()
#1 /Applications/MAMP/htdocs/dolphin/install/index.php(407): InstallPageContent('')
#2 {main}
  thrown in /Applications/MAMP/htdocs/dolphin/install/index.php on line 1350


Suggestions?

**Comment by AlexTr** [comment]
@begrafx Current official release isn't compatible with PHP 7, we have the development version which is compatible, but it isn't released yet:
https://github.com/boonex/dolphin.pro - PHP 7 compatible dev version isn't officially released yet
https://github.com/boonex/dolphin.pro/tree/7.3 - PHP 5 compatible current official version

**Comment by begrafx** [comment]
Any idea when a PHP 7 compatible version will be released?

**Comment by AlexTr** [comment]
@begrafx we don't have any ETA for now, however we have dolphin successor, which is compatible with PHP 7 - https://una.io

**Comment by alar77** [comment]
Issue is that php 7 dropped mysql extension for msqli. 
There is a 1 to 1 mapping for methods, but  while fixing Dolphin core should be easy, you cant be sure that 3d party modules never use mysql calls.

**Comment by AlexTr** [comment]
@begrafx I think not yet, actually I have no such information
